### PR TITLE
Update mythicmobs

### PR DESCRIPTION
**Pull request by 0tickpulse**

### CODE REVIEW

**Comment by 0tickpulse** [comment]
(from 5.0.2 to 5.1.4)

**Review by tal5 — APPROVED** [review]
Note that the free version on spigot is behind this one, this is the latest free version from their own download website.
As long as you made sure current Depenizen code works/compiles with this version, lgtm.

**Comment by 0tickpulse** [comment]
I don't think the Spigot version is updated as frequently, I got mine from https://mythiccraft.io/index.php?pages/official-mythicmobs-download/

(edit: oh, you mentioned that already)

**Comment by tal5** [comment]
Don't seem to have perms, but this can be closed now

**Pull request closed without merging**
